### ISSUE TITLE
predict future flight paths in Ol3

### ISSUE THREAD

**Issue by sueRimn** [geoffmcl/map-test2#1]
How to predict future flight paths in Ol3 based on the plane's current speed and heading?

**Comment by geoffmcl** [comment]
@sueRimn wow, have not touched this repo in years... `Some OpenLayers and crossfeed tests and experiments...` ... virtually dormant now...

If you are referring to my flightgear Ol3 map from http://geoffair.org/fg/map-test2/map-test.html, where, when you select in the list, and double click an active flying aircraft, you end up in `tracker.html`, with a FID, etc, and here I will paint a redline, `style2`, for the predicted path, then you can check out the javascript contained in that file, [add_predicted](https://github.com/geoffmcl/map-test2/blob/gh-pages/tracker.html#L376). 

Thus given the (lat, lon, hdg, spd), I calculate the estimated new position, using [getDirect( lat, lon, hdg, dist_km );](https://github.com/geoffmcl/map-test2/blob/gh-pages/js/geodesic.js#L284), and paint the `style2` line on the map... add a feature... and done...

But maybe I do not understand the question...

HTH

**Comment by sueRimn** [comment]
thank you @geoffmcl

**Comment by sueRimn** [comment]
> @sueRimn wow, have not touched this repo in years... `Some OpenLayers and crossfeed tests and experiments...` ... virtually dormant now...
> 
> If you are referring to my flightgear Ol3 map from http://geoffair.org/fg/map-test2/map-test.html, where, when you select in the list, and double click an active flying aircraft, you end up in `tracker.html`, with a FID, etc, and here I will paint a redline, `style2`, for the predicted path, then you can check out the javascript contained in that file, [add_predicted](https://github.com/geoffmcl/map-test2/blob/gh-pages/tracker.html#L376).
> 
> Thus given the (lat, lon, hdg, spd), I calculate the estimated new position, using [getDirect( lat, lon, hdg, dist_km );](https://github.com/geoffmcl/map-test2/blob/gh-pages/js/geodesic.js#L284), and paint the `style2` line on the map... add a feature... and done...
> 
> But maybe I do not understand the question...
> 
> HTH

I have a question, how to realize that the forecast line and the historical track line are respectively independent? When the plane passes the forecast line, the passing point will become the coordinate point of the track line.Can you give me some good advice? Thank you.

**Comment by geoffmcl** [comment]
@sueRimn not sure I completely understand the question... but will try...

> ... the forecast line and the historical track line are respectively independent?

Well, the historic track is a permanent line feature, added to the map, extended by one segment, growing, each time the new data places the plane at a new position... the forecast line is only one single line segment, and the previous feature is **deleted** before adding the current... 

So they are very **independent**... although they are both added/deleted to/from the same `lineLayer`...

The track is just a growing line of segments, 1. position A to pos B, 2. then B to C, 3. C to D, 4. ... and so on...

The forecast is just one segment. First 1. pos B to a calculated estimated pos, then 2. that is deleted, and replaced with pos C to next est. pos, then 3. del and put D to est.... an so on, ... while the position data arrives...

The forcast position never becomes anything to do with the track line... 

HTH.

PS: No need to repeat my text in your reply/question... this is a linear list of stored comments... also no need to `re-open` the issue... I get a copy of every post, regardless of the comment's `status`...
